nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['https://pcxtremedaw.com', 'http://pcxtremedaw.com']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Link']
        max_age: 3600
        allow_credentials: true
    paths:
        '^/api/':
            allow_origin: ['https://pcxtremedaw.com', 'http://pcxtremedaw.com']
            allow_headers: ['Content-Type', 'Authorization']
            allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
            allow_credentials: true
